<?php
// Add more lessons by appending rows. Code examples and answers are always English.
return [
 ['java-1','java',['Variables','المتغيرات'],
  ['A variable stores information. In Java you write the type, then the name, then the value.','المتغير يخزن معلومة. في جافا تكتب النوع ثم الاسم ثم القيمة.'],
  'int age = 15;',
  ['Create an integer variable called age with the value 15.','أنشئ متغيرًا من النوع int اسمه age وقيمته 15.'],
  '/^intage=15;?$/'],
 ['java-2','java',['Data types','أنواع البيانات'],
  ['String stores text, int whole numbers, double decimals, and boolean true or false.','النوع String يخزن النص، وint الأعداد الصحيحة، وdouble الأعداد العشرية، وboolean القيمة true أو false.'],
  'String name = "Alex";',
  ['Create a String variable called name that stores your name.','أنشئ متغيرًا من النوع String اسمه name يخزن اسمك.'],
  '/^stringname=".+";?$/'],
 ['java-3','java',['If statements','جمل الشرط'],
  ['An if statement lets a program make decisions based on a condition.','جملة if تسمح للبرنامج باتخاذ قرارات بناءً على شرط.'],
  "if (age >= 18) {\n    System.out.println(\"Adult\");\n}",
  ['Write an if statement that prints Adult when age is greater than or equal to 18.','اكتب جملة if تطبع Adult عندما تكون age أكبر من أو تساوي 18.'],
  '/if\(age>=18\)\{?system\.out\.println\("adult"\);?\}?/'],
 ['java-4','java',['Loops','الحلقات'],
  ['A loop repeats code. A for loop has a start, a condition and a step.','الحلقة تكرر الكود. حلقة for لها بداية وشرط وخطوة.'],
  "for (int i = 0; i < 5; i++) {\n    System.out.println(i);\n}",
  ['Write a for loop that runs 5 times from 0 and prints i.','اكتب حلقة for تعمل 5 مرات بدءًا من 0 وتطبع i.'],
  '/for\(inti=0;i<5;i\+\+\)\{?system\.out\.println\(i\);?\}?/'],
 ['html-1','html',['Headings','العناوين'],
  ['HTML describes the structure of a page with tags. h1 is the main heading.','تصف HTML هيكل الصفحة باستخدام الوسوم. الوسم h1 هو العنوان الرئيسي.'],
  '<h1>Hello</h1>',
  ['Write an h1 heading that says Welcome.','اكتب عنوانًا h1 يحتوي على الكلمة Welcome.'],
  '/^<h1>welcome<\/h1>$/'],
 ['html-2','html',['Links','الروابط'],
  ['The a tag creates a link. Its href attribute holds the address.','الوسم a ينشئ رابطًا، والخاصية href تحمل العنوان.'],
  '<a href="https://example.com">Visit</a>',
  ['Write a link to https://example.com with the text Visit.','اكتب رابطًا إلى https://example.com بالنص Visit.'],
  '/^<ahref="https:\/\/example\.com">visit<\/a>$/'],
 ['css-1','css',['Colors','الألوان'],
  ['CSS styles HTML. A rule has a selector and properties inside braces.','تنسّق CSS عناصر HTML. القاعدة لها محدد وخصائص بين الأقواس.'],
  "p {\n    color: red;\n}",
  ['Write a rule that makes every p element blue.','اكتب قاعدة تجعل كل عناصر p باللون الأزرق.'],
  '/^p\{color:blue;?\}$/'],
 ['js-1','js',['Variables','المتغيرات'],
  ['JavaScript uses let to declare a variable that can change.','تستخدم JavaScript الكلمة let لتعريف متغير يمكن تغييره.'],
  'let count = 0;',
  ['Declare a variable called count with let and set it to 0.','عرّف متغيرًا اسمه count باستخدام let وقيمته 0.'],
  '/^letcount=0;?$/'],
 ['php-1','php',['Variables','المتغيرات'],
  ['PHP variables start with a dollar sign and need no type.','تبدأ متغيرات PHP بعلامة الدولار ولا تحتاج إلى نوع.'],
  '$name = "Sara";',
  ['Create a variable called name that stores the text Sara.','أنشئ متغيرًا اسمه name يخزن النص Sara.'],
  '/^\$name="sara";?$/'],
];
